import type { Metadata } from 'next';
import { ArrowRight,BookOpen,ChartNoAxesColumnIncreasing,Feather,Check,MessageCircle,Package,Files,Truck,ShoppingBag,Wallet,Mail } from 'lucide-react';
import { ancienPauvre as content } from '@/content/ancien-pauvre';
import { ExcerptReader,Testimonials,LandingOrderForm } from '@/components/ancien-pauvre/Interactions';
import s from './landing.module.css';
export const metadata:Metadata={metadataBase:new URL(process.env.SITE_URL || 'http://127.0.0.1:3009'),title:'L’ancien pauvre — Entre deux vols | Salah Eddine Mimouni',description:'Découvrez le récit autobiographique de Salah Eddine Mimouni : parcours, extraits du manuscrit et demande de commande.',openGraph:{title:'L’ancien pauvre — Entre deux vols',description:'Un parcours inspirant, entre défis, résilience et dépassement de soi.',type:'book',images:[{url:content.cover,alt:'Entre deux vols — couverture fournie par Salah Eddine Mimouni'}]}};
function OrderLink({light=false,children='Commander maintenant'}:{light?:boolean;children?:React.ReactNode}){return <a className={light?s.lightButton:s.darkButton} href="#commander">{children}<ArrowRight size={18}/></a>;}
function BookMockup({className=''}:{className?:string}){return <div className={`${s.bookMockup} ${className}`}><img src={content.cover} alt="Couverture fournie : Entre deux vols — Récits d’un esprit en transit" width={1131} height={1600} loading="lazy"/></div>;}
export default function AncienPauvrePage(){
 const icons={book:BookOpen,pages:Files,edition:Package,message:MessageCircle};
 return <div className={s.page}><main id="contenu-livre">
 <section className={s.hero} id="accueil-livre"><div className={s.heroInner}><div className={s.heroPortrait}><img src={content.portrait} alt="Portrait de Salah Eddine Mimouni" width={1942} height={2560} fetchPriority="high"/></div><div className={s.heroCopy}><p className={s.authorName}>{content.author}</p><h1>L’ANCIEN<br/>PAUVRE</h1><p className={s.heroSubtitle}>(ENTRE DEUX VOLS)</p><span className={s.goldRule}/><p className={s.heroIntro}>Un parcours inspirant, entre défis, <br/>résilience et dépassement de soi.</p><figure className={s.heroQuote}><blockquote>« {content.heroQuote.text} »</blockquote><figcaption>{content.heroQuote.credit}</figcaption></figure><div className={s.signatureSpace}>Signature originale à fournir</div></div><div className={s.heroBook}><BookMockup/><span className={s.assetCaption}>Couverture fournie · Entre deux vols</span></div><div className={s.heroArguments}><div><BookOpen/><span>Une histoire<br/>personnelle</span></div><div><ChartNoAxesColumnIncreasing/><span>Des réflexions<br/>concrètes</span></div><div><Feather/><span>Une quête<br/>de sens</span></div></div></div></section>
 <section className={s.information} aria-label="Informations sur le livre"><div className={s.informationInner}>{content.information.map(item=>{const Icon=icons[item.icon as keyof typeof icons];return <div key={item.title}><Icon size={29}/><p><strong>{item.title}</strong><span>{item.text}</span></p></div>;})}</div></section>
 <section className={`${s.presentation} ${s.container}`} id="le-livre"><div className={s.bookPair}><BookMockup/><div className={s.backPlaceholder}><BookOpen size={30}/><span>Quatrième de couverture</span><small>Visuel officiel à fournir</small></div><p className={s.pairCaption}>Mockup composé avec la couverture fournie. La version noire de la maquette reste à fournir.</p></div><div className={s.presentationCopy}><h2>Plus qu’un récit,<br/>une quête de sens.</h2><p>{content.summary}</p><ul>{content.arguments.map(argument=><li key={argument}><Check size={16}/>{argument}</li>)}</ul><OrderLink/></div></section>
 <section className={s.editorialBand}><div className={s.editorialInner}><div><strong>15</strong><span>chapitres</span></div><div><strong>Une vie</strong><span>à raconter</span></div><div><strong>1</strong><span>parcours personnel</span></div><figure><blockquote>« Ce qui restait, c’était les relations, les souvenirs partagés, et le temps bien utilisé. »</blockquote><figcaption>Chapitre 13 · p. 148 du manuscrit</figcaption></figure></div></section>
 <section className={s.excerpts} id="extraits"><div className={s.excerptCopy}><p className={s.eyebrow}>EXTRAIT</p><h2>Un avant-goût de l’histoire</h2><blockquote>« {content.excerpts[0].text} »</blockquote><p className={s.excerptSource}>{content.excerpts[0].source}</p><ExcerptReader/></div><div className={s.openBookPlaceholder}><BookOpen size={62} strokeWidth={1}/><span>Le livre ouvert</span><p>Photographie à fournir</p><small>Emplacement visuel provisoire</small></div></section>
 <section className={`${s.reviews} ${s.container}`} id="temoignages"><Testimonials/></section>
 <section className={s.authorSection} id="auteur"><div className={s.authorPhoto}><img src={content.portrait} alt="Salah Eddine Mimouni, auteur" width={1942} height={2560} loading="lazy"/></div><div className={s.authorCopy}><p className={s.eyebrow}>L’AUTEUR</p><h2>Salah Eddine Mimouni</h2><p>Ingénieur d’État en informatique, entrepreneur, auteur et conférencier, Salah Eddine Mimouni partage à travers ce livre un regard personnel sur son parcours, les épreuves traversées et sa quête de sens.</p><a className={s.darkButton} href="/a-propos">Découvrir son parcours<ArrowRight size={18}/></a></div><div className={s.authorSignature}><p>Des expériences<br/>pour inspirer<br/>demain.</p><small>Emplacement réservé<br/>à la signature originale</small></div></section>
 <section className={`${s.orderSection} ${s.container}`} id="commander"><div className={s.orderVisual}><BookMockup/></div><div className={s.orderCopy}><p className={s.eyebrow}>COMMANDER LE LIVRE</p><h2>Recevez votre exemplaire</h2><p>Préparez votre demande avec les informations ci-dessous.</p><ul><li><ShoppingBag/><div>Prix : <strong>{content.commerce.price} {content.commerce.currency}</strong><small>Prix du livre, hors livraison</small></div></li><li><Truck/><div>{content.commerce.delivery}<small>{content.commerce.timing}</small></div></li><li><Wallet/><div>{content.commerce.payment}<small>Aucun paiement en ligne dans cet aperçu</small></div></li></ul><a className={s.email} href={`mailto:${content.commerce.recipient}`}><Mail size={17}/>{content.commerce.recipient}</a></div><LandingOrderForm/></section>
 </main></div>;
}
