import { ContentLanguage } from '@/components/i18n/ContentLanguage';
import type { Locale } from '@/lib/i18n';
import { getTranslator, localizeContent } from '@/lib/translate';
import { LocalizedLink } from '@/components/i18n/LocalizedLink';
import type { Metadata } from 'next';
import { ArrowRight,BookOpen,ChartNoAxesColumnIncreasing,Feather,Check,MessageCircle,Package,Files,Truck,ShoppingBag,Wallet,Mail } from 'lucide-react';
import { ancienPauvre as originalContent } from '@/content/ancien-pauvre';
import { ExcerptReader,Testimonials,LandingOrderForm } from '@/components/ancien-pauvre/Interactions';
import s from '@/app/livres/lancien-pauvre/landing.module.css';
const content = originalContent;
export const metadata:Metadata={title:'L’ancien pauvre — Entre deux vols | Salah-Eddine MIMOUNI',description:'Découvrez le récit autobiographique de Salah-Eddine MIMOUNI : parcours, extraits du manuscrit et demande de commande.',openGraph:{title:'L’ancien pauvre — Entre deux vols',description:'Un parcours inspirant, entre défis, résilience et dépassement de soi.',type:'book',images:[{url:content.cover,alt:'Entre deux vols — couverture fournie par Salah-Eddine MIMOUNI'}]}};
function OrderLink({light=false,children,locale='fr'}:{light?:boolean;children?:React.ReactNode;locale?:Locale}){const t=getTranslator(locale);return <LocalizedLink className={light?s.lightButton:s.darkButton} href="#commander">{children || t('Commander maintenant')}<ArrowRight size={18}/></LocalizedLink>;}
function BookMockup({className='',locale='fr'}:{className?:string;locale?:Locale}){const t=getTranslator(locale);return <div className={`${s.bookMockup} ${className}`}><img src={content.cover} alt={t("Couverture fournie : Entre deux vols — Récits d’un esprit en transit")} width={1131} height={1600} loading="lazy"/></div>;}
export default function AncienPauvreContent({ locale = 'fr' }: { locale?: Locale }) {
 const t = getTranslator(locale);
 const content = localizeContent(originalContent, locale);
 const icons={book:BookOpen,pages:Files,edition:Package,message:MessageCircle};
 return <div className={s.page}><main id="contenu-livre">
 <section className={s.hero} id="accueil-livre"><div className={s.heroInner}><div className={s.heroPortrait}><img src={content.portrait} alt={t("Portrait de Salah-Eddine MIMOUNI")} width={1942} height={2560} fetchPriority="high"/></div><div className={s.heroCopy}><p className={s.authorName}>{content.author}</p><h1 lang="fr">L’ANCIEN<br/>PAUVRE</h1><p className={s.heroSubtitle}>(ENTRE DEUX VOLS)</p><ContentLanguage locale={locale} kind="book"/><span className={s.goldRule}/><p className={s.heroIntro}>{t("Un parcours inspirant, entre défis, ")}<br/>{t("résilience et dépassement de soi.")}</p><figure className={s.heroQuote}><blockquote>« {content.heroQuote.text} »</blockquote><figcaption>{content.heroQuote.credit}{locale === "en" && " · Translated from French"}</figcaption></figure><div className={s.signatureSpace}>{t("Signature originale à fournir")}</div></div><div className={s.heroBook}><BookMockup locale={locale}/><span className={s.assetCaption}>{t("Couverture fournie · Entre deux vols")}</span></div><div className={s.heroArguments}><div><BookOpen/><span>{t("Une histoire")}<br/>{t("personnelle")}</span></div><div><ChartNoAxesColumnIncreasing/><span>{t("Des réflexions")}<br/>{t("concrètes")}</span></div><div><Feather/><span>{t("Une quête")}<br/>{t("de sens")}</span></div></div></div></section>
 <section className={s.information} aria-label={t("Informations sur le livre")}><div className={s.informationInner}>{content.information.map(item=>{const Icon=icons[item.icon as keyof typeof icons];return <div key={item.title}><Icon size={29}/><p><strong>{item.title}</strong><span>{item.text}</span></p></div>;})}</div></section>
 <section className={`${s.presentation} ${s.container}`} id="le-livre"><div className={s.presentationVisual}><BookMockup locale={locale}/></div><div className={s.presentationCopy}><h2>{t("Plus qu’un récit,")}<br/>{t("une quête de sens.")}</h2><p>{content.summary}</p><ul>{content.arguments.map(argument=><li key={argument}><Check size={16}/>{argument}</li>)}</ul><OrderLink locale={locale}/></div></section>
 <section className={s.editorialBand}><div className={s.editorialInner}><div><strong>15</strong><span>{t("chapitres")}</span></div><div><strong>{t("Une vie")}</strong><span>{t("à raconter")}</span></div><div><strong>1</strong><span>{t("parcours personnel")}</span></div><figure><blockquote>{t("« Ce qui restait, c’était les relations, les souvenirs partagés, et le temps bien utilisé. »")}</blockquote><figcaption>{t("Chapitre 13 · p. 148 du manuscrit")}{locale === "en" && " · Translated from French"}</figcaption></figure></div></section>
 <section className={s.excerpts} id="extraits"><div className={s.excerptCopy}><p className={s.eyebrow}>{t("EXTRAIT")}</p><h2>{t("Un avant-goût de l’histoire")}</h2><ContentLanguage locale={locale} kind="excerpt"/><blockquote>« {content.excerpts[0].text} »</blockquote><p className={s.excerptSource}>{content.excerpts[0].source}</p><ExcerptReader/></div><div className={s.openBookPlaceholder}><BookOpen size={62} strokeWidth={1}/><span>{t("Le livre ouvert")}</span><p>{t("Photographie à fournir")}</p><small>{t("Emplacement visuel provisoire")}</small></div></section>
 <section className={`${s.reviews} ${s.container}`} id="temoignages"><Testimonials/></section>
 <section className={s.authorSection} id="auteur"><div className={s.authorPhoto}><img src={content.portrait} alt={t("Salah-Eddine MIMOUNI, auteur")} width={1942} height={2560} loading="lazy"/></div><div className={s.authorCopy}><p className={s.eyebrow}>{t("L’AUTEUR")}</p><h2>Salah-Eddine MIMOUNI</h2><p>{t("Ingénieur d’État en informatique, entrepreneur, auteur et conférencier, Salah-Eddine MIMOUNI partage à travers ce livre un regard personnel sur son parcours, les épreuves traversées et sa quête de sens.")}</p><LocalizedLink className={s.darkButton} href="/a-propos">{t("Découvrir son parcours")}<ArrowRight size={18}/></LocalizedLink></div><div className={s.authorSignature}><p>{t("Des expériences")}<br/>{t("pour inspirer")}<br/>{t("demain.")}</p><small>{t("Emplacement réservé")}<br/>{t("à la signature originale")}</small></div></section>
 <section className={`${s.orderSection} ${s.container}`} id="commander"><div className={s.orderVisual}><BookMockup locale={locale}/></div><div className={s.orderCopy}><p className={s.eyebrow}>{t("COMMANDER LE LIVRE")}</p><h2>{t("Recevez votre exemplaire")}</h2><p>{t("Préparez votre demande avec les informations ci-dessous.")}</p><ul><li><ShoppingBag/><div>{t("Prix : ")}<strong>{content.commerce.price} {content.commerce.currency}</strong><small>{t("Prix du livre, hors livraison")}</small></div></li><li><Truck/><div>{content.commerce.delivery}<small>{content.commerce.timing}</small></div></li><li><Wallet/><div>{content.commerce.payment}<small>{t("Aucun paiement en ligne dans cet aperçu")}</small></div></li></ul><LocalizedLink className={s.email} href={`mailto:${content.commerce.recipient}`}><Mail size={17}/>{content.commerce.recipient}</LocalizedLink></div><LandingOrderForm/></section>
 </main></div>;
}
