import { ContentLanguage } from '@/components/i18n/ContentLanguage';
import type { Locale } from '@/lib/i18n';
import { getTranslator, localizeContent } from '@/lib/translate';
import { LocalizedLink } from '@/components/i18n/LocalizedLink';
import type { Metadata } from 'next';
import { ArrowRight, ArrowDown, ArrowUpRight, Quote } from 'lucide-react';
import { SectionReveal } from '@/components/SectionReveal';
import { library as originalLibrary } from '@/content/library';
import { contactLink } from '@/content/contact';
import s from '@/app/livres/library.module.css';
const library = originalLibrary;
export const metadata: Metadata = { title: 'Livres — Salah-Eddine MIMOUNI', description: 'Trois livres, des regards qui se croisent : L’ancien pauvre — Entre deux vols, Quand les marques pensent et Pour un like de plus… Découvrez les ouvrages de Salah-Eddine MIMOUNI.' };
export default function LibraryContent({ locale = 'fr' }: { locale?: Locale }) {
 const t = getTranslator(locale);
 const library = localizeContent(originalLibrary, locale);return <div className={s.page}><main id="library-main">
<section className={s.hero}><div className={`${s.frame} ${s.heroGrid}`}><div className={s.heroCopy}><p className={s.eyebrow}>{t("MES LIVRES")}</p><h1>{t("Trois livres.")}<br/>{t("Des regards")}<br/><em>{t("qui se croisent.")}</em></h1><p className={s.intro}>{library.intro}</p><div className={s.actions}><LocalizedLink className="button" href="#bibliotheque">{t("Découvrir mes livres")}<ArrowDown size={18}/></LocalizedLink><LocalizedLink className={s.textLink} href="/a-propos">{t("À propos de l’auteur")}<ArrowUpRight size={14}/></LocalizedLink></div></div><div className={s.collection}><div className={s.covers}>{library.books.map((book,i)=><LocalizedLink href={book.href} key={book.href} className={s.heroBook} aria-label={t`Découvrir ${book.title}`}><img src={book.cover} alt={t`Couverture originale de ${book.title}${i===0?' — Entre deux vols':''}`} loading="eager" fetchPriority={i===1?'high':'auto'}/></LocalizedLink>)}</div><p>{t("LIRE · COMPRENDRE · TRANSMETTRE")}</p></div></div></section>
<div className={s.topics}><div className={s.frame}>{library.books.map(book=><span key={book.tone}>{book.category}</span>)}</div></div>
<section id="bibliotheque" className={`${s.frame} ${s.library}`}><div className={s.sectionHeading}><div><p className={s.eyebrow}>{t("LA BIBLIOTHÈQUE")}</p><h2>{t("Choisissez votre prochaine lecture.")}</h2></div><p>{t("Découvrez l’univers de chaque ouvrage.")}</p></div><SectionReveal className={s.cards}>{library.books.map((book,i)=><article key={book.href} className={`${s.card} ${s[book.tone]} section-reveal-item`} data-reveal="visible"><LocalizedLink href={book.href} className={s.coverPanel} aria-label={t`Découvrir ${book.title}`}><span aria-hidden="true">0{i+1}</span><img src={book.cover} alt={t`Couverture originale de ${book.title}`} loading="lazy"/></LocalizedLink><div className={s.cardBody}><p className={s.category}>{book.category}</p><h3><LocalizedLink href={book.href}>{book.title}</LocalizedLink></h3><p className={s.subtitle}>{book.subtitle}</p><p className={s.summary}>{book.summary}</p><ContentLanguage locale={locale} kind="book"/><div className={s.cardActions}><LocalizedLink className="button" href={book.href}>{t("Découvrir le livre")}<ArrowRight size={19}/></LocalizedLink><LocalizedLink className={s.orderLink} href={`${book.href}#commander`}>{t("Commander")}<ArrowUpRight size={13}/></LocalizedLink></div></div></article>)}</SectionReveal></section>
<section className={s.excerpts}><div className={s.frame}><h2>{t("Quelques lignes, avant de choisir.")}</h2><ContentLanguage locale={locale} kind="excerpt"/><div className={s.quotes}>{library.excerpts.map(excerpt=><figure key={excerpt.source}><Quote size={26} aria-hidden="true"/><div><blockquote>{excerpt.text}</blockquote><figcaption>{excerpt.source}</figcaption></div></figure>)}</div></div></section>
<section className={`${s.frame} ${s.author}`}><img className={s.portrait} src={library.portrait} alt={t("Portrait original de Salah-Eddine MIMOUNI")} loading="lazy" width={1942} height={2560}/><div><p className={s.eyebrow}>{t("L’AUTEUR")}</p><h2>Salah-Eddine MIMOUNI</h2><p>{t("Ingénieur d’État en informatique, doctorant en intelligence artificielle, entrepreneur, auteur et conférencier.")}<br/>{t("Des expériences personnelles et professionnelles qui nourrissent une réflexion sur l’humain, les marques et notre époque.")}</p><LocalizedLink className={s.textLink} href="/a-propos">{t("Découvrir mon parcours")}<ArrowRight size={16}/></LocalizedLink></div><aside className={s.publisher}><p className={s.eyebrow}>{t("LA MAISON D’ÉDITION")}</p><h3>Les Éditions<br/>Actuelles</h3><p>{t("La maison d’édition de ces trois ouvrages.")}</p><img src={library.publisherLogo} alt={t("Les Éditions Actuelles — logo officiel")} loading="lazy" width={199} height={59}/></aside></section>
<section className={s.contact}><div className={s.frame}><div><p className={s.eyebrow}>{t("PROLONGEONS LA CONVERSATION")}</p><h2>{t("Un livre peut aussi ouvrir une rencontre.")}</h2><p>{t("Pour une rencontre littéraire, une interview ou un échange autour des ouvrages.")}</p></div><LocalizedLink className="button" href={contactLink('litteraire')}>{t("Me contacter")}<ArrowRight size={19}/></LocalizedLink></div></section>
</main></div>}
