import { ContentLanguage } from '@/components/i18n/ContentLanguage';
import type { Locale } from '@/lib/i18n';
import { getTranslator, localizeContent } from '@/lib/translate';
import { LocalizedLink } from '@/components/i18n/LocalizedLink';
import type {Metadata} from 'next';
import {ArrowRight,ArrowUpRight,Asterisk,Plus} from 'lucide-react';
import {marques as originalContent} from '@/content/marques';
import {MarquesForm} from '@/components/marques/Interactions';
import s from '@/app/livres/quand-les-marques-pensent/marques.module.css';
const c = originalContent;
export const metadata:Metadata={title:'Quand les marques pensent — Salah-Eddine MIMOUNI',description:c.subtitle,alternates:{canonical:'/livres/quand-les-marques-pensent'},openGraph:{title:c.title,description:c.subtitle,type:'book',images:[{url:c.cover,width:692,height:1024,alt:'Couverture originale de Quand les marques pensent'}]},twitter:{card:'summary_large_image',title:c.title,description:c.subtitle,images:[c.cover]}};
function Logo(){return <img className={s.logo} src={c.logo} width={199} height={59} alt="Les Éditions Actuelles"/>;}
function Cover({hero=false,locale='fr'}:{hero?:boolean;locale?:Locale}){const t=getTranslator(locale);return <img className={hero?s.heroCover:s.smallCover} src={c.cover} width={692} height={1024} alt={t("Quand les marques pensent — couverture originale")} loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'}/>;}
function OrderLink({locale='fr'}:{locale?:Locale}){const t=getTranslator(locale);return <LocalizedLink className={s.primary} href="#commander">{t("Commander le livre")}<ArrowRight size={18}/></LocalizedLink>;}
export default function MarquesContent({ locale = 'fr' }: { locale?: Locale }) {
 const t = getTranslator(locale);
 const c = localizeContent(originalContent, locale);return <div className={s.page}><main id="livre-contenu">
<section className={s.hero} id="accueil"><div className={`${s.frame} ${s.heroGrid}`}><div className={s.heroCopy}><p className={s.eyebrow}>{t("MARKETING · INTELLIGENCE ARTIFICIELLE")}</p><h1 lang="fr">Quand les<br/><em>marques</em><br/>pensent.</h1><p className={s.subtitle}>{t("La révolution de l’IA qui bouleverse")}<br/>{t("le marketing et l’influence.")}</p><ContentLanguage locale={locale} kind="book"/><p className={s.byline}>{t("Un livre de Salah-Eddine MIMOUNI")}</p><div className={s.actions}><OrderLink locale={locale}/><LocalizedLink className={s.secondary} href="#extraits">{t("Lire un extrait")}<ArrowUpRight size={19}/></LocalizedLink></div><p className={s.publication}>{t("Une publication des Éditions Actuelles")}</p></div><div className={s.bookStage}><img className={s.network} src="/assets/books/marques-network.webp" width={222} height={265} alt="" aria-hidden="true"/><Cover hero locale={locale}/><div className={s.pedestal} aria-hidden="true"/><p>{t("PENSER. COMPRENDRE. TRANSFORMER.")}</p></div></div></section>
<section className={s.facts} aria-label={t("Repères du livre")}><div className={s.frame}>{c.facts.map(([number,title,text])=><div key={title}><span>{number}</span><p><strong>{title}</strong><small>{text}</small></p></div>)}</div></section>
<section className={`${s.frame} ${s.introduction}`} id="le-livre"><div><p className={s.eyebrow}>{t("LE LIVRE")}</p><h2>{t("Le marketing a changé")}<br/>{t("de monde.")}<br/><em>{t("Et votre marque ?")}</em></h2></div><div><p className={s.introText}>{c.intro}</p><div className={s.axes}>{c.axes.map(([title,text])=><div key={title}><Asterisk size={18} aria-hidden="true"/><p><strong>{title}</strong><span>{text}</span></p></div>)}</div></div></section>
<section className={s.contents} id="sommaire"><div className={s.frame}><div className={s.sectionHeading}><div><p className={s.eyebrow}>{t("À L’INTÉRIEUR")}</p><h2>{t("Trois actes pour changer de perspective.")}</h2></div><p>{t("De la fin des anciens réflexes")}<br/>{t("à la marque qui pense vraiment.")}</p></div><div className={s.acts}>{c.acts.map((act,index)=><article key={act.label} className={index===1?s.darkAct:undefined}><div className={s.actHeading}><p className={s.eyebrow}>{act.label}</p><span>0{index+1}</span></div><h3>{act.title}</h3><ol start={act.start}>{act.chapters.map((title,i)=><li key={title}><span>{String(act.start+i).padStart(2,'0')}</span>{title}</li>)}</ol></article>)}</div><div className={s.contentsFoot}><p>{t("Des concepts, des récits de terrain et des méthodes pour nourrir votre réflexion.")}</p><div>{['VITA','REACT','Brand DNA','BrandGPT'].map(tag=><span key={tag}>{tag}</span>)}</div></div></div></section>
<section className={`${s.frame} ${s.excerpts}`} id="extraits"><div className={s.sectionHeading}><div><p className={s.eyebrow}>{t("EXTRAITS DU LIVRE")}</p><h2>{t("Quelques lignes pour commencer.")}</h2></div><LocalizedLink href="#le-livre">{t("Découvrir le livre")}<ArrowRight size={17}/></LocalizedLink></div><ContentLanguage locale={locale} kind="excerpt"/><div className={s.quotes}>{c.excerpts.map(e=><figure key={e.source}><span aria-hidden="true">“</span><div><blockquote>{e.text}</blockquote><figcaption>{e.source}</figcaption></div></figure>)}</div></section>
<section className={s.manifesto}><div className={s.frame}><Asterisk size={73} strokeWidth={1} aria-hidden="true"/><blockquote>{t("« Dans un monde où l’IA produit tout,")}<br/><em>{t("la seule rareté est la pensée.")}</em> »</blockquote><span>QUAND LES MARQUES PENSENT</span></div></section>
<section className={`${s.frame} ${s.authorSection}`}><div className={s.author} id="auteur"><img src={c.portrait} alt="Salah-Eddine MIMOUNI" width={1942} height={2560} loading="lazy"/><div><p className={s.eyebrow}>{t("L’AUTEUR")}</p><h2>Salah-Eddine MIMOUNI</h2><p className={s.authorRole}>{t("Ingénieur · Entrepreneur · Auteur · Conférencier")}</p><p>{c.bio}</p><LocalizedLink href="/a-propos">{t("À la croisée du marketing, de l’IA et de l’humain")}<ArrowRight size={17}/></LocalizedLink></div></div><aside className={s.publisher} id="editeur"><p className={s.eyebrow}>{t("LA MAISON D’ÉDITION")}</p><h2>Les Éditions<br/>Actuelles</h2><p>{t("La maison d’édition de")}<br/><i>Quand les marques pensent.</i></p><Logo/></aside><div className={s.reviews}><h3>{t("Vous l’avez lu ? Votre regard compte.")}</h3><p>{t("Un espace accueillera les témoignages de lecteurs après réception et validation.")}</p><span>{t("AVIS À VENIR")}</span></div></section>
<section className={s.order} id="commander"><div className={`${s.frame} ${s.orderGrid}`}><div className={s.orderCopy}><p className={s.eyebrow}>{t("COMMANDER LE LIVRE")}</p><h2>{t("La prochaine idée")}<br/>{t("commence peut-être")}<br/><em>{t("dans ces pages.")}</em></h2><p>{t("Demandez votre exemplaire en renseignant le formulaire. Les modalités de vente vous seront précisées avant toute confirmation.")}</p><div className={s.orderBook}><Cover locale={locale}/><div><h3>Quand les marques<br/>pensent</h3><p>Salah-Eddine MIMOUNI<br/>Les Éditions Actuelles</p></div></div><p className={s.terms}><strong>{t("Prix : ")}{c.commerce.price}{t(" Dhs l’exemplaire.")}</strong><br/>{t("Frais de livraison : à confirmer.")}<br/><span>{c.commerce.payment}</span></p></div><MarquesForm/></div></section>
<section className={`${s.frame} ${s.faq}`}><div><p className={s.eyebrow}>{t("AVANT DE TOURNER LA PAGE")}</p><h2>{t("Quelques réponses,")}<br/>{t("avant votre lecture.")}</h2></div><div>{c.faq.map(([question,answer], index)=><details key={question}><summary>{question}<Plus size={16}/></summary><p>{answer}{index === 1&&<> <LocalizedLink href="#extraits">{t("Lire les extraits.")}</LocalizedLink></>}{index === 2&&<> <LocalizedLink href={`mailto:${c.commerce.recipient}`}>{t("Contacter l’auteur.")}</LocalizedLink></>}</p></details>)}</div></section>
</main></div>;}
