import { ContentLanguage } from '@/components/i18n/ContentLanguage';
import type { Locale } from '@/lib/i18n';
import { getTranslator, localizeContent } from '@/lib/translate';
import { LocalizedLink } from '@/components/i18n/LocalizedLink';
import { ArrowRight, ArrowDown, Users, ShoppingCart, Eye, UserRound, Video, Check, BookOpen, Heart } from 'lucide-react';
import type { Book } from '@/content/books';
import { books as originalBooks } from '@/content/books';
import { OrderForm } from '@/components/books/OrderForm';
import { SectionReveal } from '@/components/SectionReveal';
import s from './Influence.module.css';
export function InfluenceLanding({book:originalBook,orderingEnabled,locale='fr'}:{book:Book;orderingEnabled:boolean;locale?:Locale}){
 const t=getTranslator(locale), book=localizeContent(originalBook,locale), books=localizeContent(originalBooks,locale);
const themeIcons=[Users,ShoppingCart,Eye], editorialIcons=[UserRound,ShoppingCart,Video];
return <div className={s.page}><main id="like-main">
<section className={s.hero}><div className={`${s.frame} ${s.heroGrid}`}><div className={s.heroCopy}><p className={s.eyebrow}>{t("NOUVEAU LIVRE")}</p><h1 lang="fr">Pour un<br/><span className={s.like}>[<b>LIKE</b>]</span> de plus…</h1><p className={s.subtitle}>{book.subtitle}</p><ContentLanguage locale={locale} kind="book"/><p className={s.intro}>{t("Et si chaque like avait un prix ?")}<br/>{book.description}</p><div className={s.price}><strong>{book.price} <small>{t("Dhs")}</small></strong><span>{t("L’exemplaire")}<br/>{t("Frais de livraison à confirmer")}</span></div><div className={s.actions}><LocalizedLink className={s.primary} href="#commander">{t("Commander le livre")}<ArrowRight size={18}/></LocalizedLink><LocalizedLink className={s.secondary} href="#decouvrir">{t("Découvrir le livre")}<ArrowDown size={18}/></LocalizedLink></div><div className={s.heroNotes}><span><BookOpen size={15}/>{t("Société & influence")}</span><span>Les Éditions Actuelles</span><span>{t("Édition en français")}</span></div></div><div className={s.bookScene}><div className={s.bookMockup}><img src={book.image} alt={t`Couverture originale de ${book.title}`} width={1024} height={1536} fetchPriority="high"/></div><span className={`${s.notification} ${s.heartOne}`} aria-hidden="true"><Heart fill="currentColor"/></span><span className={`${s.notification} ${s.heartTwo}`} aria-hidden="true"><Heart fill="currentColor"/></span><span className={`${s.notification} ${s.heartThree}`} aria-hidden="true"><Heart fill="currentColor"/></span><p className={s.sceneNote}>{t("PLUS QU’UN LIVRE,")}<br/>{t("UN REGARD SUR")}<br/>{t("NOTRE ÉPOQUE.")}</p></div></div></section>
<section className={s.light} id="decouvrir"><div className={s.frame}><div className={s.overview}><div><p className={s.eyebrow}>{t("À PROPOS DU LIVRE")}</p><h2>{t("Un livre.")}<br/>{t("Une autre perspective.")}</h2></div><p>{book.introduction}</p></div><SectionReveal className={s.cards}>{book.themes.map((theme,i)=>{const Icon=themeIcons[i];return <article className="section-reveal-item" data-reveal="visible" key={theme.title}><div className={s.number}>0{i+1}<Icon size={27}/></div><h3>{theme.title}</h3><p>{theme.text}</p></article>})}</SectionReveal></div></section>
<section className={s.dark} id="extraits"><div className={s.frame}><div className={s.sectionHeading}><div><p className={s.eyebrow}>{t("ÉCLAIRAGES")}</p><h2>{t("Ce que l’influence nous coûte.")}</h2></div><p>{t("Aperçus éditoriaux proposés pour cette page à partir des thèmes indiqués par l’auteur. Ces textes ne sont pas des extraits du manuscrit.")}</p></div><SectionReveal className={`${s.cards} ${s.editorial}`}>{book.editorialPreviews?.map((item,i)=>{const Icon=editorialIcons[i];return <article className="section-reveal-item" data-reveal="visible" key={item.title}><div className={s.number}>0{i+1}<Icon size={27}/></div><h3>{item.title}</h3><p>{item.paragraphs[0]}</p><details><summary>{t("Poursuivre la réflexion")}</summary>{item.paragraphs.slice(1).map(p=><p key={p}>{p}</p>)}</details></article>})}</SectionReveal></div></section>
<section className={s.light}><div className={`${s.frame} ${s.author}`}><img src="/assets/photos/portrait.jpeg" width={1942} height={2560} alt={t("Portrait original de Salah-Eddine MIMOUNI")} loading="lazy"/><div><p className={s.eyebrow}>{t("L’AUTEUR")}</p><h2>Salah-Eddine MIMOUNI</h2><p>{t("Entrepreneur, auteur et conférencier. À travers ses livres, il ouvre un espace de réflexion sur le parcours humain, le marketing et l’influence.")}</p><LocalizedLink href="/a-propos">{t("En savoir plus sur l’auteur")}<ArrowRight size={17}/></LocalizedLink></div><aside><span>{t("PRENDRE DU RECUL")}</span><p>{t("Le parcours humain.")}<br/>{t("Le marketing.")}<br/>{t("L’influence.")}</p></aside></div></section>
<section className={`${s.dark} ${s.order}`} id="commander"><div className={`${s.frame} ${s.orderGrid}`}><div className={s.orderCopy}><p className={s.eyebrow}>{t("COMMANDER LE LIVRE")}</p><h2>{t("La lecture commence")}<br/>{t("par une rencontre.")}</h2><p>{t("Recevez les informations nécessaires pour commander votre exemplaire de ")}<strong>{book.title}</strong>.</p><ul><li><Check size={18}/>{book.price}{t(" Dhs par exemplaire")}</li><li><Check size={18}/>{t("De 1 à 10 exemplaires")}</li><li><Check size={18}/>{t("Frais de livraison à confirmer")}</li><li><Check size={18}/>{t("Livraison et règlement confirmés par email")}</li></ul><div className={s.price}><strong>{book.price} <small>{t("Dhs")}</small></strong></div><LocalizedLink className={s.contact} href="mailto:sd.mimouni@richmedia.ma">sd.mimouni@richmedia.ma</LocalizedLink></div><div className={s.form}><OrderForm slug={book.slug} title={book.title} price={book.price} collectAddress orderingEnabled={orderingEnabled}/></div></div></section>
<section className={s.light}><div className={`${s.frame} ${s.faq}`}><div><p className={s.eyebrow}>{t("QUESTIONS FRÉQUENTES")}</p><h2>{t("Avant de commander.")}</h2><p>{t("Toutes les réponses à vos questions.")}</p></div><div><details><summary>{t("Comment se passe la commande ?")}</summary><p>{orderingEnabled?t("Envoyez votre demande. Nous vous recontacterons par email pour confirmer la disponibilité du livre, la livraison et le mode de règlement."):t("Le formulaire est actuellement en mode démonstration : aucune demande n’est transmise. Pour commander, écrivez à sd.mimouni@richmedia.ma. La disponibilité, la livraison et le règlement seront confirmés par email.")}{t(" Aucun paiement n’est demandé sur cette page.")}</p></details><details><summary>{t("Quels sont les délais de livraison ?")}</summary><p>{t("Les délais et frais de livraison seront précisés par email selon votre destination, avant confirmation de la commande.")}</p></details><details><summary>{t("Puis-je commander plusieurs exemplaires ?")}</summary><p>{t("Oui, jusqu’à 10 exemplaires par formulaire. Pour davantage d’exemplaires ou plusieurs titres, écrivez à sd.mimouni@richmedia.ma.")}</p></details><details id="donnees-commande"><summary>{t("Comment sont utilisées mes coordonnées ?")}</summary><p>{orderingEnabled?t("Vos coordonnées et votre message sont transmis à sd.mimouni@richmedia.ma par notre prestataire d’email transactionnel pour traiter la demande et vous répondre."):t("En mode démonstration, vos coordonnées ne sont ni envoyées ni enregistrées.")}{t(" Aucune inscription à une newsletter. Vous pouvez demander la suppression des données transmises en écrivant à cette adresse.")}</p></details></div></div></section>
<section className={s.dark}><div className={`${s.frame} ${s.related}`}><div><p className={s.eyebrow}>{t("CONTINUER LA DÉCOUVERTE")}</p><h2>{t("D’autres regards")}<br/>{t("sur notre époque.")}</h2></div>{books.filter(b=>b.slug!==book.slug).map(b=><LocalizedLink href={b.slug==='entre-deux-vols'?'/livres/lancien-pauvre':`/livres/${b.slug}`} key={b.slug}><img src={b.jacket?'/assets/books/marques-front.webp':b.image} alt={t`Couverture de ${b.title}`} loading="lazy"/><div><h3>{b.alias?`${b.alias} — ${b.title}`:b.title}</h3><p>{b.subtitle}</p><span>{t("Découvrir le livre")}<ArrowRight size={15}/></span></div></LocalizedLink>)}</div></section>
</main></div>
}
