import { ArrowRight, ArrowDown, Users, ShoppingCart, Eye, UserRound, Video, Check, BookOpen, Heart } from 'lucide-react';
import type { Book } from '@/content/books';
import { books } from '@/content/books';
import { OrderForm } from '@/components/books/OrderForm';
import { SectionReveal } from '@/components/SectionReveal';
import s from './Influence.module.css';
export function InfluenceLanding({book,orderingEnabled}:{book:Book;orderingEnabled:boolean}){
const themeIcons=[Users,ShoppingCart,Eye], editorialIcons=[UserRound,ShoppingCart,Video];
return <div className={s.page}><main id="like-main">
<section className={s.hero}><div className={`${s.frame} ${s.heroGrid}`}><div className={s.heroCopy}><p className={s.eyebrow}>NOUVEAU LIVRE</p><h1>Pour un<br/><span className={s.like}>[<b>LIKE</b>]</span> de plus…</h1><p className={s.subtitle}>{book.subtitle}</p><p className={s.intro}>Et si chaque like avait un prix ?<br/>{book.description}</p><div className={s.price}><strong>{book.price} <small>Dhs</small></strong><span>L’exemplaire<br/>Frais de livraison à confirmer</span></div><div className={s.actions}><a className={s.primary} href="#commander">Commander le livre<ArrowRight size={18}/></a><a className={s.secondary} href="#decouvrir">Découvrir le livre<ArrowDown size={18}/></a></div><div className={s.heroNotes}><span><BookOpen size={15}/>Société & influence</span><span>Les Éditions Actuelles</span><span>Édition en français</span></div></div><div className={s.bookScene}><div className={s.bookMockup}><img src={book.image} alt={`Couverture originale de ${book.title}`} width={1024} height={1536} fetchPriority="high"/></div><span className={`${s.notification} ${s.heartOne}`} aria-hidden="true"><Heart fill="currentColor"/></span><span className={`${s.notification} ${s.heartTwo}`} aria-hidden="true"><Heart fill="currentColor"/></span><span className={`${s.notification} ${s.heartThree}`} aria-hidden="true"><Heart fill="currentColor"/></span><p className={s.sceneNote}>PLUS QU’UN LIVRE,<br/>UN REGARD SUR<br/>NOTRE ÉPOQUE.</p></div></div></section>
<section className={s.light} id="decouvrir"><div className={s.frame}><div className={s.overview}><div><p className={s.eyebrow}>À PROPOS DU LIVRE</p><h2>Un livre.<br/>Une autre perspective.</h2></div><p>{book.introduction}</p></div><SectionReveal className={s.cards}>{book.themes.map((theme,i)=>{const Icon=themeIcons[i];return <article className="section-reveal-item" data-reveal="visible" key={theme.title}><div className={s.number}>0{i+1}<Icon size={27}/></div><h3>{theme.title}</h3><p>{theme.text}</p></article>})}</SectionReveal></div></section>
<section className={s.dark} id="extraits"><div className={s.frame}><div className={s.sectionHeading}><div><p className={s.eyebrow}>ÉCLAIRAGES</p><h2>Ce que l’influence nous coûte.</h2></div><p>Aperçus éditoriaux proposés pour cette page à partir des thèmes indiqués par l’auteur. Ces textes ne sont pas des extraits du manuscrit.</p></div><SectionReveal className={`${s.cards} ${s.editorial}`}>{book.editorialPreviews?.map((item,i)=>{const Icon=editorialIcons[i];return <article className="section-reveal-item" data-reveal="visible" key={item.title}><div className={s.number}>0{i+1}<Icon size={27}/></div><h3>{item.title}</h3><p>{item.paragraphs[0]}</p><details><summary>Poursuivre la réflexion</summary>{item.paragraphs.slice(1).map(p=><p key={p}>{p}</p>)}</details></article>})}</SectionReveal></div></section>
<section className={s.light}><div className={`${s.frame} ${s.author}`}><img src="/assets/photos/portrait.jpeg" width={1942} height={2560} alt="Portrait original de Salah Eddine Mimouni" loading="lazy"/><div><p className={s.eyebrow}>L’AUTEUR</p><h2>Salah Eddine Mimouni</h2><p>Entrepreneur, auteur et conférencier. À travers ses livres, il ouvre un espace de réflexion sur le parcours humain, le marketing et l’influence.</p><a href="/a-propos">En savoir plus sur l’auteur<ArrowRight size={17}/></a></div><aside><span>PRENDRE DU RECUL</span><p>Le parcours humain.<br/>Le marketing.<br/>L’influence.</p></aside></div></section>
<section className={`${s.dark} ${s.order}`} id="commander"><div className={`${s.frame} ${s.orderGrid}`}><div className={s.orderCopy}><p className={s.eyebrow}>COMMANDER LE LIVRE</p><h2>La lecture commence<br/>par une rencontre.</h2><p>Recevez les informations nécessaires pour commander votre exemplaire de <strong>{book.title}</strong>.</p><ul><li><Check size={18}/>{book.price} Dhs par exemplaire</li><li><Check size={18}/>De 1 à 10 exemplaires</li><li><Check size={18}/>Frais de livraison à confirmer</li><li><Check size={18}/>Livraison et règlement confirmés par email</li></ul><div className={s.price}><strong>{book.price} <small>Dhs</small></strong></div><a className={s.contact} href="mailto:sd.mimouni@richmedia.ma">sd.mimouni@richmedia.ma</a></div><div className={s.form}><OrderForm slug={book.slug} title={book.title} price={book.price} collectAddress orderingEnabled={orderingEnabled}/></div></div></section>
<section className={s.light}><div className={`${s.frame} ${s.faq}`}><div><p className={s.eyebrow}>QUESTIONS FRÉQUENTES</p><h2>Avant de commander.</h2><p>Toutes les réponses à vos questions.</p></div><div><details><summary>Comment se passe la commande ?</summary><p>{orderingEnabled?'Envoyez votre demande. Nous vous recontacterons par email pour confirmer la disponibilité du livre, la livraison et le mode de règlement.':'Le formulaire est actuellement en mode démonstration : aucune demande n’est transmise. Pour commander, écrivez à sd.mimouni@richmedia.ma. La disponibilité, la livraison et le règlement seront confirmés par email.'} Aucun paiement n’est demandé sur cette page.</p></details><details><summary>Quels sont les délais de livraison ?</summary><p>Les délais et frais de livraison seront précisés par email selon votre destination, avant confirmation de la commande.</p></details><details><summary>Puis-je commander plusieurs exemplaires ?</summary><p>Oui, jusqu’à 10 exemplaires par formulaire. Pour davantage d’exemplaires ou plusieurs titres, écrivez à sd.mimouni@richmedia.ma.</p></details><details id="donnees-commande"><summary>Comment sont utilisées mes coordonnées ?</summary><p>{orderingEnabled?'Vos coordonnées et votre message sont transmis à sd.mimouni@richmedia.ma par notre prestataire d’email transactionnel pour traiter la demande et vous répondre.':'En mode démonstration, vos coordonnées ne sont ni envoyées ni enregistrées.'} Aucune inscription à une newsletter. Vous pouvez demander la suppression des données transmises en écrivant à cette adresse.</p></details></div></div></section>
<section className={s.dark}><div className={`${s.frame} ${s.related}`}><div><p className={s.eyebrow}>CONTINUER LA DÉCOUVERTE</p><h2>D’autres regards<br/>sur notre époque.</h2></div>{books.filter(b=>b.slug!==book.slug).map(b=><a href={b.slug==='entre-deux-vols'?'/livres/lancien-pauvre':`/livres/${b.slug}`} key={b.slug}><img src={b.jacket?'/assets/books/marques-front.webp':b.image} alt={`Couverture de ${b.title}`} loading="lazy"/><div><h3>{b.alias?`${b.alias} — ${b.title}`:b.title}</h3><p>{b.subtitle}</p><span>Découvrir le livre<ArrowRight size={15}/></span></div></a>)}</div></section>
</main></div>
}
