import type { Locale } from '@/lib/i18n';

export const commonCopy = {
  fr: {
    contactEyebrow: 'DES PROJETS QUI ONT DU SENS', contactTitle: 'Une conférence, un podcast ou un projet ?',
    contactInvitation: 'Parlons-en.', contactDescription: 'Je suis toujours ouvert aux échanges, aux collaborations et aux nouvelles opportunités.',
    contact: 'Me contacter', contactMissing: 'Coordonnées de contact à renseigner',
    studio: 'Salah-Eddine MIMOUNI au micro, en studio', signature: 'Entrepreneur · Auteur · Conférencier',
    notesTitle: 'À compléter avant publication',
    notesDescription: 'Cette page est un aperçu local. Certains chiffres, pourcentages, éléments du parcours, citations et événements restent à valider. Les sept vidéos du catalogue Podcasts proviennent des liens YouTube fournis par l’auteur. Les photographies et la vidéo ont été fournies par Salah-Eddine MIMOUNI.',
    notesBooks: 'Extraits des manuscrits et modalités de livraison des trois livres.', notesLinks: 'CV PDF et liens des réseaux sociaux.',
    demoTitle: 'Aperçu de démonstration.', demoDescription: 'Chiffres, citation et dates des événements à valider. Photographies originales intégrées.', details: 'Détails',
    review: 'À valider', linkMissing: 'Lien à renseigner', originalCover: 'Couverture originale de',
    testimonial: 'The Bridge · Témoignage', watchTestimonial: 'Voir le témoignage The Bridge',
    closePlayer: 'Fermer le lecteur', pause: 'Pause', play: 'Lecture', pauseLabel: 'Mettre en pause', playLabel: 'Reprendre la lecture',
    openSource: 'Ouvrir la source', externalEpisode: 'Cet épisode se découvre directement sur sa plateforme.',
    videoError: 'La vidéo ne peut pas être lue ici. Ouvrez-la sur sa plateforme.',
    playerError: 'Le lecteur externe est indisponible. Utilisez le lien vers la source.',
    autoplayError: 'Appuyez sur Lecture dans le lecteur pour démarrer, ou ouvrez la source.',
    episodeError: 'Cet épisode est indisponible dans le lecteur. Utilisez le lien vers la source.',
    playbackError: 'Lecture indisponible. Utilisez le lien vers la source.',
    localVideoError: 'Cette vidéo est indisponible. Utilisez le lien vers la source.',
    audioError: 'Cet audio est indisponible. Utilisez le lien vers la source.',
  },
  en: {
    contactEyebrow: 'LET’S MAKE SOMETHING MEANINGFUL', contactTitle: 'A talk, a podcast or a project?',
    contactInvitation: 'Let’s talk.', contactDescription: 'I’m always open to new conversations, collaborations and opportunities.',
    contact: 'Get in touch', contactMissing: 'Contact details not yet available',
    studio: 'Salah-Eddine MIMOUNI speaking into a microphone in the studio', signature: 'Entrepreneur · Author · Speaker',
    notesTitle: 'Content awaiting confirmation',
    notesDescription: 'Some figures, career details, quotations and event information are still awaiting confirmation. The seven videos in the podcast catalogue come from YouTube links supplied by the author. The photographs and video were provided by Salah-Eddine MIMOUNI.',
    notesBooks: 'Manuscript excerpts and delivery details for the three books.', notesLinks: 'PDF CV and social media links.',
    demoTitle: 'Preview content.', demoDescription: 'Some figures and quotations are awaiting confirmation. Original photographs are used throughout.', details: 'Details',
    review: 'Awaiting confirmation', linkMissing: 'Link not yet available', originalCover: 'Original cover of',
    testimonial: 'The Bridge · Testimonial', watchTestimonial: 'Watch The Bridge testimonial',
    closePlayer: 'Close player', pause: 'Pause', play: 'Play', pauseLabel: 'Pause playback', playLabel: 'Resume playback',
    openSource: 'Open original', externalEpisode: 'Watch or listen to this episode on its original platform.',
    videoError: 'This video cannot be played here. Open it on its original platform.',
    playerError: 'The external player is unavailable. Please use the link to the original.',
    autoplayError: 'Press Play to start, or open the original.',
    episodeError: 'This episode cannot be played here. Please use the link to the original.',
    playbackError: 'Playback is unavailable. Please use the link to the original.',
    localVideoError: 'This video is unavailable. Please use the link to the original.',
    audioError: 'This audio is unavailable. Please use the link to the original.',
  },
} satisfies Record<Locale, Record<string, string>>;
