'use client';
import { useRef,useState,type FormEvent } from 'react';
import { ArrowRight,ArrowLeft,Menu,X } from 'lucide-react';
import { ancienPauvre as content,validateLandingOrder,type LandingOrder } from '@/content/ancien-pauvre';
import styles from '@/app/livres/lancien-pauvre/landing.module.css';
export function LandingNavigation(){
 const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);
 return <><button className={styles.menuToggle} ref={toggle} aria-label={open?'Fermer le menu':'Ouvrir le menu'} aria-expanded={open} aria-controls="lp-menu" onClick={()=>setOpen(!open)} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);}}>{open?<X/>:<Menu/>}</button><nav id="lp-menu" className={`${styles.navigation} ${open?styles.navigationOpen:''}`} aria-label="Navigation du livre" onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}}}>{content.navigation.map(([label,href])=><a href={href} key={href} onClick={()=>setOpen(false)}>{label}</a>)}</nav></>;
}
export function ExcerptReader(){
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 return <><button ref={trigger} className={styles.darkButton} onClick={()=>dialog.current?.showModal()}>Lire d’autres extraits<ArrowRight size={18}/></button><dialog ref={dialog} className={styles.reader} aria-labelledby="lp-reader-title" onClose={()=>trigger.current?.focus()} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><div className={styles.readerHeader}><div><span className={styles.eyebrow}>LECTURE</span><h2 id="lp-reader-title">Quelques pages, quelques mots.</h2></div><button autoFocus onClick={()=>dialog.current?.close()} aria-label="Fermer les extraits"><X/></button></div>{content.excerpts.map(excerpt=><article key={excerpt.title}><h3>{excerpt.title}</h3><blockquote>« {excerpt.text} »</blockquote><p>{excerpt.source}</p></article>)}<small>Passages du manuscrit « L’ancien pauvre — Quand Tout Ne Suffit Pas », version finale 6.0. La pagination indiquée est celle de ce manuscrit.</small></dialog></>;
}
export function Testimonials(){
 const [start,setStart]=useState(0);const reviews=content.testimonials;const total=reviews.length;const visible=total?Array.from({length:Math.min(3,total)},(_,i)=>reviews[(start+i)%total]):[];
 return <><div className={styles.reviewsHeading}><div><p className={styles.eyebrow}>TÉMOIGNAGES</p><h2>Ils en parlent mieux que nous</h2></div><div className={styles.reviewControls}><button aria-label="Témoignages précédents" disabled={total<=3} onClick={()=>setStart((start-1+total)%total)}><ArrowLeft size={20}/></button><button aria-label="Témoignages suivants" disabled={total<=3} onClick={()=>setStart((start+1)%total)}><ArrowRight size={20}/></button></div></div><div className={styles.reviewsGrid}>{total?visible.map((review,i)=><article key={`${review.name}-${i}`}><p>« {review.text} »</p><strong>{review.name}</strong><small>{review.role}</small></article>):[1,2,3].map(i=><article key={i}><span className={styles.reviewIndex}>0{i}</span><h3>Témoignage à fournir</h3><p>Cet espace accueillera un avis authentique, publié avec l’accord de son auteur.</p><small>Aperçu · aucun avis publié</small></article>)}</div></>;
}
const initial:LandingOrder={name:'',phone:'',city:'',address:'',quantity:'1',consent:false};
export function LandingOrderForm(){
 const [values,setValues]=useState(initial),[errors,setErrors]=useState<ReturnType<typeof validateLandingOrder>>({}),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const form=useRef<HTMLFormElement>(null);const lock=useRef(false);const result=useRef<HTMLDivElement>(null);
 const update=(key:keyof LandingOrder,value:string|boolean)=>{setValues(v=>({...v,[key]:value}));setNotice('');};
 async function submit(event:FormEvent){event.preventDefault();if(lock.current)return;const checked=validateLandingOrder(values);setErrors(checked);setNotice('');if(Object.keys(checked).length){requestAnimationFrame(()=>form.current?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());return;}lock.current=true;setBusy(true);await new Promise(resolve=>setTimeout(resolve,250));setNotice('Démonstration : les champs sont valides. Aucune commande n’a été envoyée ni enregistrée. Pour commander, contactez directement '+content.commerce.recipient+'.');setBusy(false);lock.current=false;requestAnimationFrame(()=>result.current?.focus());}
 const field=(name:'name'|'phone'|'city'|'address',label:string,autocomplete:string)=><label className={name==='address'||name==='city'?styles.fullField:undefined} htmlFor={`lp-${name}`}>{label} *{name==='address'?<textarea id={`lp-${name}`} aria-label={`${label} *`} required maxLength={500} autoComplete={autocomplete} value={values[name]} onChange={e=>update(name,e.target.value)} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`lp-${name}-error`:undefined}/>:<input id={`lp-${name}`} aria-label={`${label} *`} required type={name==='phone'?'tel':'text'} maxLength={name==='phone'?25:100} autoComplete={autocomplete} value={values[name]} onChange={e=>update(name,e.target.value)} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`lp-${name}-error`:undefined}/>} {errors[name]&&<span id={`lp-${name}-error`} className={styles.fieldError}>{errors[name]}</span>}</label>;
 const quantity=Number(values.quantity);const subtotal=Number.isInteger(quantity)&&quantity>=1&&quantity<=content.commerce.maxQuantity?quantity*content.commerce.price:null;
 return <form ref={form} className={styles.orderForm} onSubmit={submit} noValidate aria-label="Commander L’ancien pauvre"><p className={styles.demoLabel}>Aperçu du formulaire · envoi non activé</p><fieldset disabled={busy}><legend className={styles.srOnly}>Vos coordonnées</legend><div className={styles.formGrid}>{field('name','Nom complet','name')}{field('phone','Téléphone','tel')}{field('city','Ville','address-level2')}{field('address','Adresse de livraison','street-address')}<label className={styles.fullField} htmlFor="lp-quantity">Quantité *<input id="lp-quantity" aria-label="Quantité *" type="number" required min="1" max={content.commerce.maxQuantity} step="1" value={values.quantity} onChange={e=>update('quantity',e.target.value)} aria-invalid={!!errors.quantity} aria-describedby={errors.quantity?'lp-quantity-error':undefined}/>{errors.quantity&&<span id="lp-quantity-error" className={styles.fieldError}>{errors.quantity}</span>}</label></div><p className={styles.total}>Sous-total livres <strong>{subtotal===null?'—':`${subtotal} ${content.commerce.currency}`}</strong></p><small>Frais de livraison non inclus, à confirmer.</small><label className={styles.consent}><input type="checkbox" checked={values.consent} onChange={e=>update('consent',e.target.checked)} aria-invalid={!!errors.consent} aria-describedby={errors.consent?'lp-consent-error':undefined}/>J’accepte que mes coordonnées soient utilisées pour traiter ma demande.</label>{errors.consent&&<span className={styles.fieldError} id="lp-consent-error">{errors.consent}</span>}<button className={styles.darkButton} type="submit">{busy?'Vérification…':'Commander maintenant'}<ArrowRight size={18}/></button></fieldset><div ref={result} tabIndex={-1} role="status" className={notice?styles.formNotice:undefined}>{notice}</div><p className={styles.privacy}>Dans cet aperçu, vos informations restent uniquement dans le formulaire et sont effacées au rechargement. Aucun paiement n’est effectué.</p></form>;
}
