import { ArrowRight } from 'lucide-react';
import { home } from '@/content/home';
import { Brand, SourceAction } from './primitives';
import { SectionReveal } from './SectionReveal';
import styles from './Contact.module.css';
export function Contact() {
  return <section id="contact" className={styles.section} aria-labelledby="contact-title"><SectionReveal className={styles.frame}><div className={`${styles.card} section-reveal-item`} data-reveal="visible"><div className={styles.content}><p className={styles.eyebrow}>DES PROJETS QUI ONT DU SENS</p><h2 id="contact-title">Une conférence, un podcast ou un projet&nbsp;?<br/><span>Parlons-en.</span></h2><p className={styles.description}>{home.contactDescription}</p><SourceAction href={home.contactUrl} unavailable="Coordonnées de contact à renseigner" className={styles.button}>Me contacter<ArrowRight size={20}/></SourceAction></div><figure className={styles.photo}><img src="/assets/photos/studio.jpg" alt="Salah-Eddine Mimouni au micro, en studio" width={5351} height={3567} loading="lazy"/><figcaption>Salah-Eddine Mimouni<span>Entrepreneur · Auteur · Conférencier</span></figcaption></figure></div></SectionReveal></section>;
}
export function Footer({ active = 'Accueil', clean = false }: { active?: string; clean?: boolean }) {
  const icons = ['/assets/social-linkedin.webp', '/assets/social-youtube.webp', '/assets/social-instagram.webp'];
  return <><SectionReveal className="footer-reveal"><footer className="footer section-reveal-item" data-reveal="visible"><Brand/><nav aria-label="Navigation de pied de page">{home.nav.map(([label,href]) => <a href={href} key={label} aria-current={active === label ? 'page' : undefined}>{label}</a>)}</nav><div className="socials">{home.socials.filter(item=>item.url).map((item,i) => { const icon = icons[home.socials.indexOf(item)]; return item.url ? <a href={item.url} key={item.name} aria-label={item.name}><img src={icon} width={16} height={16} alt=""/></a> : <button disabled key={item.name} aria-label={`${item.name} — lien non renseigné`} title={`${item.name} — lien à renseigner`}><img src={icon} width={16} height={16} alt=""/></button>; })}</div><small>© {new Date().getFullYear()} Salah-Eddine Mimouni. Tous droits réservés.</small></footer></SectionReveal>{!clean && <details id="contenus" className="content-notes"><summary>À compléter avant publication</summary><p>Cette page est un aperçu local. Certains chiffres, pourcentages, éléments du parcours, citations et événements restent à valider. Les sept vidéos du catalogue Podcasts proviennent des liens YouTube fournis par l’auteur. Les photographies et la vidéo ont été fournies par Salah-Eddine Mimouni.</p><ul><li>Extraits des manuscrits et modalités de livraison des trois livres.</li><li>CV PDF et liens des réseaux sociaux.</li></ul></details>}</>;
}
