'use client';
import {useState,useRef,type FormEvent} from 'react';
import {ArrowRight,Menu,X} from 'lucide-react';
import {marques,validateMarquesRequest,type MarquesRequest} from '@/content/marques';
import s from '@/app/livres/quand-les-marques-pensent/marques.module.css';
export function MarquesNav(){
 const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);
 const close=()=>{setOpen(false);toggle.current?.focus();};
 return <div className={s.navWrapper} onKeyDown={e=>{if(e.key==='Escape')close();}}><button ref={toggle} className={s.menuButton} aria-label={open?'Fermer le menu':'Ouvrir le menu'} aria-expanded={open} aria-controls="marques-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav id="marques-menu" className={`${s.nav} ${open?s.navOpen:''}`} aria-label="Navigation du livre">{marques.navigation.map(([label,href])=><a href={href} key={href} onClick={()=>setOpen(false)}>{label}</a>)}<a className={s.mobileOrder} href="#commander" onClick={()=>setOpen(false)}>Commander le livre</a></nav></div>;
}
export function MarquesForm(){
 const [v,setV]=useState<MarquesRequest>({book:marques.id,name:'',phone:'',email:'',city:'',address:'',quantity:'1',consent:false});
 const [errors,setErrors]=useState<Partial<Record<keyof MarquesRequest,string>>>({});
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const locked=useRef(false),form=useRef<HTMLFormElement>(null),result=useRef<HTMLParagraphElement>(null);
 const change=(name:keyof MarquesRequest,value:string|boolean)=>{setV(p=>({...p,[name]:value}));setErrors(p=>({...p,[name]:undefined}));setNotice('');};
 async function submit(event:FormEvent){event.preventDefault();if(locked.current)return;const found=validateMarquesRequest(v);setErrors(found);setNotice('');if(Object.keys(found).length){requestAnimationFrame(()=>form.current?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());return;}locked.current=true;setBusy(true);try{await new Promise(resolve=>setTimeout(resolve,300));setNotice('Démonstration : votre formulaire est valide. Aucune demande n’a été envoyée ni enregistrée. Pour commander, contactez sd.mimouni@richmedia.ma.');requestAnimationFrame(()=>result.current?.focus());}finally{setBusy(false);locked.current=false;}}
 const field=(name:'name'|'phone'|'email'|'city'|'address',label:string,placeholder:string,autocomplete:string)=><label className={name==='address'?s.fullField:undefined} htmlFor={`marques-${name}`}><span>{label}</span>{name==='address'?<textarea id={`marques-${name}`} aria-label={label} required autoComplete={autocomplete} maxLength={500} placeholder={placeholder} value={v[name]} onChange={e=>change(name,e.target.value)} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`marques-${name}-error`:undefined}/>:<input id={`marques-${name}`} aria-label={label} required={name!=='email'} type={name==='phone'?'tel':name==='email'?'email':'text'} autoComplete={autocomplete} maxLength={name==='email'?254:name==='phone'?25:100} placeholder={placeholder} value={v[name]} onChange={e=>change(name,e.target.value)} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`marques-${name}-error`:undefined}/>} {errors[name]&&<span className={s.error} id={`marques-${name}-error`}>{errors[name]}</span>}</label>;
 return <form className={s.form} ref={form} noValidate onSubmit={submit} aria-labelledby="marques-form-title"><h3 id="marques-form-title">Recevoir mon exemplaire</h3><p className={s.formIntro}>Vos coordonnées pour le suivi de votre demande.</p><p className={s.demo}>Mode démonstration · envoi non activé</p><input type="hidden" name="book" value={marques.id}/><fieldset disabled={busy}><legend className={s.srOnly}>Vos coordonnées</legend><div className={s.fields}>{field('name','Nom complet *','Votre nom et prénom','name')}{field('phone','Téléphone *','Votre numéro de téléphone','tel')}{field('email','E-mail (facultatif)','Votre adresse e-mail','email')}{field('city','Ville *','Votre ville','address-level2')}{field('address','Adresse de livraison *','Votre adresse complète','street-address')}<label className={s.fullField} htmlFor="marques-quantity"><span>Quantité *</span><input className={s.quantity} id="marques-quantity" aria-label="Quantité *" required type="number" min="1" step="1" value={v.quantity} onChange={e=>change('quantity',e.target.value)} aria-invalid={!!errors.quantity} aria-describedby={errors.quantity?'marques-quantity-error':undefined}/>{errors.quantity&&<span className={s.error} id="marques-quantity-error">{errors.quantity}</span>}</label></div><label className={s.consent}><input type="checkbox" checked={v.consent} onChange={e=>change('consent',e.target.checked)} aria-invalid={!!errors.consent} aria-describedby={errors.consent?'marques-consent-error':undefined}/>J’accepte d’être contacté pour le suivi de ma demande.</label>{errors.consent&&<span id="marques-consent-error" className={s.error}>{errors.consent}</span>}<button className={s.primary} type="submit">{busy?'Vérification…':'Envoyer ma demande'}<ArrowRight size={19}/></button></fieldset><p ref={result} role="status" tabIndex={-1} className={notice?s.notice:s.emptyNotice}>{notice}</p><small>Aucun paiement. Prix, livraison et modalités à confirmer.<br/>Les coordonnées ne sont pas conservées au rechargement.</small></form>;
}
