'use client';
import { useTranslation } from '@/components/i18n/useTranslation';
import {useState,useRef,type FormEvent} from 'react';
import {ArrowRight,Menu,X} from 'lucide-react';
import {marques as originalMarques,validateMarquesRequest,type MarquesRequest} from '@/content/marques';
import s from '@/app/livres/quand-les-marques-pensent/marques.module.css';
export function MarquesNav(){
 const {t,locale,localize}=useTranslation();
 const marques=localize(originalMarques);
 const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);
 const close=()=>{setOpen(false);toggle.current?.focus();};
 return <div className={s.navWrapper} onKeyDown={e=>{if(e.key==='Escape')close();}}><button ref={toggle} className={s.menuButton} aria-label={open?t("Fermer le menu"):t("Ouvrir le menu")} aria-expanded={open} aria-controls="marques-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav id="marques-menu" className={`${s.nav} ${open?s.navOpen:''}`} aria-label={t("Navigation du livre")}>{marques.navigation.map(([label,href])=><a href={href} key={href} onClick={()=>setOpen(false)}>{label}</a>)}<a className={s.mobileOrder} href="#commander" onClick={()=>setOpen(false)}>{t("Commander le livre")}</a></nav></div>;
}
export function MarquesForm(){
 const {t,locale,localize}=useTranslation();
 const marques=localize(originalMarques);
 const [v,setV]=useState<MarquesRequest>({book:marques.id,name:'',phone:'',email:'',city:'',address:'',quantity:'1',consent:false});
 const [errors,setErrors]=useState<Partial<Record<keyof MarquesRequest,string>>>({});
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const locked=useRef(false),form=useRef<HTMLFormElement>(null),result=useRef<HTMLParagraphElement>(null);
 const change=(name:keyof MarquesRequest,value:string|boolean)=>{setV(p=>({...p,[name]:value}));setErrors(p=>({...p,[name]:undefined}));setNotice('');};
 async function submit(event:FormEvent){event.preventDefault();if(locked.current)return;const found=validateMarquesRequest(v);setErrors(found);setNotice('');if(Object.keys(found).length){requestAnimationFrame(()=>form.current?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());return;}locked.current=true;setBusy(true);try{await new Promise(resolve=>setTimeout(resolve,300));setNotice(t("Démonstration : votre formulaire est valide. Aucune demande n’a été envoyée ni enregistrée. Pour commander, contactez sd.mimouni@richmedia.ma."));requestAnimationFrame(()=>result.current?.focus());}finally{setBusy(false);locked.current=false;}}
 const field=(name:'name'|'phone'|'email'|'city'|'address',label:string,placeholder:string,autocomplete:string)=><label className={name==='address'?s.fullField:undefined} htmlFor={`marques-${name}`}><span>{label}</span>{name==='address'?<textarea id={`marques-${name}`} aria-label={label} required autoComplete={autocomplete} maxLength={500} placeholder={placeholder} value={v[name]} onChange={e=>change(name,e.target.value)} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`marques-${name}-error`:undefined}/>:<input id={`marques-${name}`} aria-label={label} required={name!=='email'} type={name==='phone'?'tel':name==='email'?'email':'text'} autoComplete={autocomplete} maxLength={name==='email'?254:name==='phone'?25:100} placeholder={placeholder} value={v[name]} onChange={e=>change(name,e.target.value)} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`marques-${name}-error`:undefined}/>} {errors[name]&&<span className={s.error} id={`marques-${name}-error`}>{t(errors[name]!)}</span>}</label>;
 return <form className={s.form} ref={form} noValidate onSubmit={submit} aria-labelledby="marques-form-title"><h3 id="marques-form-title">{t("Recevoir mon exemplaire")}</h3><p className={s.formIntro}>{t("Vos coordonnées pour le suivi de votre demande.")}</p><p className={s.demo}>{t("Mode démonstration · envoi non activé")}</p><input type="hidden" name="book" value={marques.id}/><fieldset disabled={busy}><legend className={s.srOnly}>{t("Vos coordonnées")}</legend><div className={s.fields}>{field('name',t("Nom complet *"),t("Votre nom et prénom"),'name')}{field('phone',t("Téléphone *"),t("Votre numéro de téléphone"),'tel')}{field('email',t("E-mail (facultatif)"),t("Votre adresse e-mail"),'email')}{field('city',t("Ville *"),t("Votre ville"),'address-level2')}{field('address',t("Adresse de livraison *"),t("Votre adresse complète"),'street-address')}<label className={s.fullField} htmlFor="marques-quantity"><span>{t("Quantité *")}</span><input className={s.quantity} id="marques-quantity" aria-label={t("Quantité *")} required type="number" min="1" step="1" value={v.quantity} onChange={e=>change('quantity',e.target.value)} aria-invalid={!!errors.quantity} aria-describedby={errors.quantity?'marques-quantity-error':undefined}/>{errors.quantity&&<span className={s.error} id="marques-quantity-error">{t(errors.quantity!)}</span>}</label></div><label className={s.consent}><input type="checkbox" checked={v.consent} onChange={e=>change('consent',e.target.checked)} aria-invalid={!!errors.consent} aria-describedby={errors.consent?'marques-consent-error':undefined}/>{t("J’accepte d’être contacté pour le suivi de ma demande.")}</label>{errors.consent&&<span id="marques-consent-error" className={s.error}>{t(errors.consent!)}</span>}<button className={s.primary} type="submit">{busy?t("Vérification…"):t("Envoyer ma demande")}<ArrowRight size={19}/></button></fieldset><p ref={result} role="status" tabIndex={-1} className={notice?s.notice:s.emptyNotice}>{notice}</p><small>{marques.commerce.price}{t(" Dhs l’exemplaire, hors livraison.")}<br/>{t("Aucun paiement. Frais et modalités de livraison à confirmer.")}<br/>{t("Les coordonnées ne sont pas conservées au rechargement.")}</small></form>;
}
