import type {Metadata} from 'next';
import {ArrowRight,ArrowUpRight,Asterisk,Plus} from 'lucide-react';
import {marques as c} from '@/content/marques';
import {MarquesForm} from '@/components/marques/Interactions';
import s from './marques.module.css';
export const metadata:Metadata={title:'Quand les marques pensent — Salah-Eddine MIMOUNI',description:c.subtitle,alternates:{canonical:'/livres/quand-les-marques-pensent'},openGraph:{title:c.title,description:c.subtitle,type:'book',images:[{url:c.cover,width:692,height:1024,alt:'Couverture originale de Quand les marques pensent'}]},twitter:{card:'summary_large_image',title:c.title,description:c.subtitle,images:[c.cover]}};
function Logo(){return <img className={s.logo} src={c.logo} width={199} height={59} alt="Les Éditions Actuelles"/>;}
function Cover({hero=false}:{hero?:boolean}){return <img className={hero?s.heroCover:s.smallCover} src={c.cover} width={692} height={1024} alt="Quand les marques pensent — couverture originale" loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'}/>;}
function OrderLink(){return <a className={s.primary} href="#commander">Commander le livre<ArrowRight size={18}/></a>;}
export default function MarquesPage(){return <div className={s.page}><main id="livre-contenu">
<section className={s.hero} id="accueil"><div className={`${s.frame} ${s.heroGrid}`}><div className={s.heroCopy}><p className={s.eyebrow}>MARKETING · INTELLIGENCE ARTIFICIELLE</p><h1>Quand les<br/><em>marques</em><br/>pensent.</h1><p className={s.subtitle}>La révolution de l’IA qui bouleverse<br/>le marketing et l’influence.</p><p className={s.byline}>Un livre de Salah-Eddine MIMOUNI</p><div className={s.actions}><OrderLink/><a className={s.secondary} href="#extraits">Lire un extrait<ArrowUpRight size={19}/></a></div><p className={s.publication}>Une publication des Éditions Actuelles</p></div><div className={s.bookStage}><img className={s.network} src="/assets/books/marques-network.webp" width={222} height={265} alt="" aria-hidden="true"/><Cover hero/><div className={s.pedestal} aria-hidden="true"/><p>PENSER. COMPRENDRE. TRANSFORMER.</p></div></div></section>
<section className={s.facts} aria-label="Repères du livre"><div className={s.frame}>{c.facts.map(([number,title,text])=><div key={title}><span>{number}</span><p><strong>{title}</strong><small>{text}</small></p></div>)}</div></section>
<section className={`${s.frame} ${s.introduction}`} id="le-livre"><div><p className={s.eyebrow}>LE LIVRE</p><h2>Le marketing a changé<br/>de monde.<br/><em>Et votre marque ?</em></h2></div><div><p className={s.introText}>{c.intro}</p><div className={s.axes}>{c.axes.map(([title,text])=><div key={title}><Asterisk size={18} aria-hidden="true"/><p><strong>{title}</strong><span>{text}</span></p></div>)}</div></div></section>
<section className={s.contents} id="sommaire"><div className={s.frame}><div className={s.sectionHeading}><div><p className={s.eyebrow}>À L’INTÉRIEUR</p><h2>Trois actes pour changer de perspective.</h2></div><p>De la fin des anciens réflexes<br/>à la marque qui pense vraiment.</p></div><div className={s.acts}>{c.acts.map((act,index)=><article key={act.label} className={index===1?s.darkAct:undefined}><div className={s.actHeading}><p className={s.eyebrow}>{act.label}</p><span>0{index+1}</span></div><h3>{act.title}</h3><ol start={act.start}>{act.chapters.map((title,i)=><li key={title}><span>{String(act.start+i).padStart(2,'0')}</span>{title}</li>)}</ol></article>)}</div><div className={s.contentsFoot}><p>Des concepts, des récits de terrain et des méthodes pour nourrir votre réflexion.</p><div>{['VITA','REACT','Brand DNA','BrandGPT'].map(tag=><span key={tag}>{tag}</span>)}</div></div></div></section>
<section className={`${s.frame} ${s.excerpts}`} id="extraits"><div className={s.sectionHeading}><div><p className={s.eyebrow}>EXTRAITS DU LIVRE</p><h2>Quelques lignes pour commencer.</h2></div><a href="#le-livre">Découvrir le livre<ArrowRight size={17}/></a></div><div className={s.quotes}>{c.excerpts.map(e=><figure key={e.source}><span aria-hidden="true">“</span><div><blockquote>{e.text}</blockquote><figcaption>{e.source}</figcaption></div></figure>)}</div></section>
<section className={s.manifesto}><div className={s.frame}><Asterisk size={73} strokeWidth={1} aria-hidden="true"/><blockquote>« Dans un monde où l’IA produit tout,<br/><em>la seule rareté est la pensée.</em> »</blockquote><span>QUAND LES MARQUES PENSENT</span></div></section>
<section className={`${s.frame} ${s.authorSection}`}><div className={s.author} id="auteur"><img src={c.portrait} alt="Salah-Eddine MIMOUNI" width={1942} height={2560} loading="lazy"/><div><p className={s.eyebrow}>L’AUTEUR</p><h2>Salah-Eddine MIMOUNI</h2><p className={s.authorRole}>Ingénieur · Entrepreneur · Auteur · Conférencier</p><p>{c.bio}</p><a href="/a-propos">À la croisée du marketing, de l’IA et de l’humain<ArrowRight size={17}/></a></div></div><aside className={s.publisher} id="editeur"><p className={s.eyebrow}>LA MAISON D’ÉDITION</p><h2>Les Éditions<br/>Actuelles</h2><p>La maison d’édition de<br/><i>Quand les marques pensent.</i></p><Logo/></aside><div className={s.reviews}><h3>Vous l’avez lu ? Votre regard compte.</h3><p>Un espace accueillera les témoignages de lecteurs après réception et validation.</p><span>AVIS À VENIR</span></div></section>
<section className={s.order} id="commander"><div className={`${s.frame} ${s.orderGrid}`}><div className={s.orderCopy}><p className={s.eyebrow}>COMMANDER LE LIVRE</p><h2>La prochaine idée<br/>commence peut-être<br/><em>dans ces pages.</em></h2><p>Demandez votre exemplaire en renseignant le formulaire. Les modalités de vente vous seront précisées avant toute confirmation.</p><div className={s.orderBook}><Cover/><div><h3>Quand les marques<br/>pensent</h3><p>Salah-Eddine MIMOUNI<br/>Les Éditions Actuelles</p></div></div><p className={s.terms}><strong>Prix : {c.commerce.price} Dhs l’exemplaire.</strong><br/>Frais de livraison : à confirmer.<br/><span>{c.commerce.payment}</span></p></div><MarquesForm/></div></section>
<section className={`${s.frame} ${s.faq}`}><div><p className={s.eyebrow}>AVANT DE TOURNER LA PAGE</p><h2>Quelques réponses,<br/>avant votre lecture.</h2></div><div>{c.faq.map(([question,answer])=><details key={question}><summary>{question}<Plus size={16}/></summary><p>{answer}{question.startsWith('Puis-je')&&<> <a href="#extraits">Lire les extraits.</a></>}{question.startsWith('Comment')&&<> <a href={`mailto:${c.commerce.recipient}`}>Contacter l’auteur.</a></>}</p></details>)}</div></section>
</main></div>;}
